name: falcon
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - faiss=1.6.5
  - fastcluster=1.1.26
  - joblib=1.0.0
  - lxml=4.6.2
  - matplotlib-base=3.3.3
  - natsort=7.1.0
  - numba=0.52.0
  - numpy=1.19.4
  - pandas=1.2.0
  - pyarrow=2.0.0
  - pyteomics=4.4.0
  - python=3.8.6
  - scikit-learn=0.24.0
  - scipy=1.5.3
  - spectrum_utils=0.3.4
  - tqdm=4.55.0
prefix: ~/.conda/envs/falcon

